In [1]:
#import requisite libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.model_selection import train_test_split
from matplotlib.colors import ListedColormap
from sklearn import metrics
from scipy.stats import multivariate_normal
import sklearn
from sklearn import datasets

In [2]:
digits = datasets.load_digits(n_class=10,as_frame=True) # Load the MNIST data
DS=digits.frame

In [3]:
# Splitting the dataset into the Training set and Test set
x_train, x_test = train_test_split(DS, test_size = 0.3, random_state = 0,stratify=DS[['target']])


In [4]:
#calculating mean, covariance and prior for all class
mean_lst = []
cov_lst = []
prior_lst = []
for i in range(10):
    x=x_train[x_train['target']==i]
    cov_0 = x.cov()
    cov_0 = np.array(cov_0.values)[:64,:64]
    x = x.to_numpy()
    mean = np.mean(x,axis=0)[:64]
    mean_lst.append(mean)
    cov_lst.append(cov_0)
    prior_lst.append(len(x)/len(x_train))

In [5]:
#predicting the value using Bayes classifier for test data and finding the accuracy 
y_pred_bayes = []
X_test = x_test.to_numpy()
for i in range(len(X_test)):
    Y = []
    for j in range(10):
        y = prior_lst[j]*(multivariate_normal.pdf(X_test[i,:64] , mean_lst[j] , cov_lst[j] , allow_singular=True))
        Y.append(y)
    y_pred_bayes.append(np.argmax(np.array(Y)))


print("Accuracy =",sklearn.metrics.accuracy_score(X_test[:,64], y_pred_bayes)*100)

# To display the Confusion matrix
print(confusion_matrix(X_test[:,64], y_pred_bayes))   

Accuracy = 94.25925925925925
[[54  0  0  0  0  0  0  0  0  0]
 [ 0 49  0  0  0  1  0  0  5  0]
 [ 0  1 47  0  0  0  0  0  5  0]
 [ 0  0  0 50  0  0  0  0  1  4]
 [ 1  0  0  0 48  0  0  2  2  1]
 [ 0  0  0  2  0 52  0  0  1  0]
 [ 0  0  0  0  0  1 53  0  0  0]
 [ 0  0  0  0  1  0  0 52  0  1]
 [ 0  0  0  1  0  0  0  0 51  0]
 [ 0  0  0  0  0  0  0  0  1 53]]
