In [1]:
#import requisite libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from matplotlib.colors import ListedColormap
from sklearn import metrics
from sklearn import datasets
import sklearn

In [2]:
digits = datasets.load_digits(n_class=10) # Load the MNIST data
x_img_data = digits.data # Images
y_img_labl = digits.target  # Corresponding labels

In [3]:
# Splitting the dataset into the Training set and Test set
X_train, X_test, y_train, y_test = train_test_split(x_img_data, y_img_labl, test_size = 0.3, random_state = 0)

# Splitting the Train set further into development and train set
X_train, X_dev, y_train, y_dev = train_test_split(X_train, y_train, test_size = 0.2, random_state = 0)


In [4]:
accuracies = [] # Store accuracies for each K, later we will see which K gives maximum accuracy.

# loop over various values of `k` for the k-Nearest Neighbor classifier
kVals = range(1, 10, 2)  # Storing the values of K used
model = {}  # Set of models

for k in range(1, 10, 2):
    # train the k-Nearest Neighbor classifier with the current value of `k`
    model[k] = KNeighborsClassifier(n_neighbors=k)
    model[k].fit(X_train, y_train.ravel())

    # evaluate the model and update the accuracies list
    score = model[k].score(X_dev,y_dev)
    print("k=%d, accuracy=%.2f%%" % (k, score * 100))
    accuracies.append(score)


# find the value of k that has the largest accuracy
bestK = int(np.argmax(accuracies))
print("\n###########   k=%d achieved highest accuracy of %.2f%% on validation data" % (kVals[bestK],accuracies[bestK] * 100))


# evaluate the model on test data
K=kVals[bestK]  # Get the value of best K
score = model[K].score(X_test, y_test)
print("The accuracy(%) on the test data using best K =",score*100)


#predicting the value using K-NN for test data and finding the accuracy
Z = model[k].predict(X_test)
print("Accuracy =",sklearn.metrics.accuracy_score(y_test, Z)*100)


# To display the Confusion matrix
print(confusion_matrix(y_test, Z)) 

k=1, accuracy=98.02%
k=3, accuracy=97.62%
k=5, accuracy=98.81%
k=7, accuracy=98.41%
k=9, accuracy=97.62%

###########   k=5 achieved highest accuracy of 98.81% on validation data
The accuracy(%) on the test data using best K = 97.96296296296296
Accuracy = 97.03703703703704
[[45  0  0  0  0  0  0  0  0  0]
 [ 0 52  0  0  0  0  0  0  0  0]
 [ 1  1 50  0  0  0  0  1  0  0]
 [ 0  0  0 53  0  0  0  0  1  0]
 [ 0  0  0  0 47  0  0  1  0  0]
 [ 0  0  0  0  0 54  1  0  0  2]
 [ 0  0  0  0  0  0 60  0  0  0]
 [ 0  0  0  0  0  0  0 53  0  0]
 [ 0  2  0  3  0  0  0  1 55  0]
 [ 0  0  0  1  0  1  0  0  0 55]]
