In [1]:
#import requisite libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from matplotlib.colors import ListedColormap
from sklearn import metrics
from sklearn import datasets
import sklearn

In [2]:
digits = datasets.load_digits(n_class=10) # Load the MNIST data
x_img_data = digits.data # Images
y_img_labl = digits.target  # Corresponding labels

In [3]:
# Splitting the dataset into the Training set and Test set
X_train, X_test, y_train, y_test = train_test_split(x_img_data, y_img_labl, test_size = 0.3, random_state = 0)

# Splitting the Train set further into development and train set
X_train, X_dev, y_train, y_dev = train_test_split(X_train, y_train, test_size = 0.2, random_state = 0)

In [4]:
#Train the SVM(Linear Kernel) 
accuracies = []
Cval = range(1,10,1)
model = {}  # Set of models
for c in range(1, 10, 1):
    model[c] = SVC(C=c,kernel='linear')
    model[c].fit(X_train, y_train.ravel())
    
    # evaluate the model and update the accuracies list
    score = model[c].score(X_dev,y_dev)
    print("C=%d, accuracy=%.2f%%" % (c, score * 100))
    accuracies.append(score)

# find the value of C that has the largest accuracy    
bestC = int(np.argmax(accuracies))
print("\n###########   best C=%d achieved highest accuracy of %.2f%% on validation data" % (Cval[bestC],accuracies[bestC] * 100))


# evaluate the model on test data
C=Cval[bestC]  # Get the value of best C
score = model[C].score(X_test, y_test)
print("The accuracy(%) on the test data using best C =",score*100)


#predicting the value using Linear kernal for test data and finding the accuracy
Z = model[c].predict(X_test)
print("Accuracy =",sklearn.metrics.accuracy_score(y_test, Z)*100)


# confusion_matrix
CM=confusion_matrix(y_test, Z) 
print(CM)


# get number of support vectors for each class
print(model[c].n_support_)  

C=1, accuracy=98.02%
C=2, accuracy=98.02%
C=3, accuracy=98.02%
C=4, accuracy=98.02%
C=5, accuracy=98.02%
C=6, accuracy=98.02%
C=7, accuracy=98.02%
C=8, accuracy=98.02%
C=9, accuracy=98.02%

###########   best C=1 achieved highest accuracy of 98.02% on validation data
The accuracy(%) on the test data using best C = 97.4074074074074
Accuracy = 97.4074074074074
[[45  0  0  0  0  0  0  0  0  0]
 [ 0 51  0  0  0  1  0  0  0  0]
 [ 0  1 52  0  0  0  0  0  0  0]
 [ 0  0  0 53  0  0  0  0  1  0]
 [ 0  0  0  0 48  0  0  0  0  0]
 [ 0  0  0  0  0 56  0  0  0  1]
 [ 0  1  0  0  0  0 59  0  0  0]
 [ 0  0  0  0  1  0  0 52  0  0]
 [ 0  1  1  1  0  0  0  0 57  1]
 [ 0  1  0  1  0  1  0  0  1 53]]
[25 35 30 29 32 33 20 31 42 48]
